# Generated by Django 5.1.3 on 2024-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_quickorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят к работе'), ('in_progress', 'Находится в работе'), ('delivering', 'В доставке'), ('completed', 'Выполнен')], default='accepted', max_length=20),
        ),
    ]
