# Generated by Django 5.1.3 on 2024-11-11 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_quickorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickorder',
            name='order_type',
            field=models.CharField(choices=[('quick', 'Быстрая покупка'), ('cart', 'Корзина')], default='cart', max_length=10),
        ),
        migrations.AddField(
            model_name='quickorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
