# Generated by Django 5.1.3 on 2024-11-11 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_orders', models.PositiveIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
