# Generated by Django 5.1.3 on 2024-11-14 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quickorder',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='quick_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.quickorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quickorder',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
