# Generated by Django 5.1.3 on 2024-11-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_order_delivery_address_remove_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickorder',
            name='quantity',
        ),
    ]
