# Generated by Django 5.1.3 on 2024-11-17 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_report_total_bouquets_report_total_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёты'},
        ),
        migrations.AlterModelOptions(
            name='reportparameter',
            options={'verbose_name': 'Параметр отчёта', 'verbose_name_plural': 'Параметры отчётов'},
        ),
        migrations.RemoveField(
            model_name='reportparameter',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл отчёта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='shop.reportparameter', verbose_name='Параметр отчёта'),
        ),
        migrations.AlterField(
            model_name='reportparameter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название параметра'),
        ),
    ]
